server:
  port: 8082
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: fraudguard

spring:
  application:
    name: notification-service
    
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.fraudguard.shared.model"
        isolation.level: read_committed
        enable.auto.commit: false
        max.poll.interval.ms: 300000
        max.poll.records: 500
        heartbeat.interval.ms: 3000
        session.timeout.ms: 10000
        
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
          
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD}
    
notification:
  config:
    retry-attempts: 3
    retry-delay: 1000
    templates-path: classpath:templates/
    default-language: en
    supported-languages: en,es,fr
    rate-limit:
      max-per-hour: 5
      max-per-day: 20

resilience4j:
  retry:
    instances:
      emailNotification:
        maxAttempts: 3
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  ratelimiter:
    instances:
      emailNotification:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms
  bulkhead:
    instances:
      emailNotification:
        maxConcurrentCalls: 20
        maxWaitDuration: 1000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        notification-latency: true
      sla:
        notification-latency: 1000ms, 5000ms, 10000ms

logging:
  level:
    root: INFO
    com.fraudguard: DEBUG
    org.springframework.kafka: INFO
    org.springframework.mail: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/notification-service.log
    max-size: 10MB
    max-history: 7
